server:
  port: 8090
spring:
  profiles:
    active: local
  application:
    name: Meal Planner Agent
  datasource:
    url: MYSQL_DB_URL
    username: USERNAME
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto=: update

# Needed only if VertexAiSessionService is used. Not needed for InMemorySessionService.
google.adk.reasoning-engine-name:
  VERTEX_AI_REASONING_ENGINE_NAME
